### ISSUE TITLE
hfc_routing structure is misleading

### ISSUE THREAD

**Issue by joshsinykin** [Infineon/ubm#1]
The mtb_stc_ubm_backplane_cfg_t structure has a substructure called hfc_routing. However the user example and name of this structure is misleading. The example implies it defines the i2c address of the HFC interface, but in reality, this structure is being used for the UBM FRU Port Route Descriptor list. 

Here is an example of how I would need to fill out the hfc_routing structure for proper UBM FRU initialization.

This listing describes 3 HFCs, HFC 0, HFC1 and HFC4. HFC0 and 1 are Segregated, where HFC4 is Converged. Note they both route similar drive_connector indexes. As you can see this structure is more than just I2C Address of an HFC. I do question what structure in the config will be used for defining my HFC listings (0,1,and 4) and the mapping of those to the SCL/SDA pins.
 

.hfc_routing =
	    {
	        { .drive_connector_idx=1, .slot_offset=1, .dfc_status_and_control=1, .drive_link_width=MTB_UBM_LINK_WIDTH_X4 , .port_type=MTB_UBM_PORT_TYPE_SEGREGATED, .domain=MTB_UBM_PORT_DOMAIN_PRIMARY, .hfc_identifier=0, .hfc_starting_phy_lane=0, .sff_ta_1001_support=1, .sas_sata_support=0, .quad_pcie_support=1, .dfc_empty=1, .ubm_ctrl_slave_addr = 0x6E, .max_sata_rate=MTB_UBM_SATA_RATE_NS, .max_sas_rate=MTB_UBM_SAS_RATE_NS, .max_pcie_rate=MTB_UBM_PCIE_5_RATE, },
			{ .drive_connector_idx=0, .slot_offset=0, .dfc_status_and_control=0, .drive_link_width=MTB_UBM_LINK_WIDTH_X4 , .port_type=MTB_UBM_PORT_TYPE_SEGREGATED, .domain=MTB_UBM_PORT_DOMAIN_PRIMARY, .hfc_identifier=0, .hfc_starting_phy_lane=4, .sff_ta_1001_support=1, .sas_sata_support=0, .quad_pcie_support=1, .dfc_empty=1, .ubm_ctrl_slave_addr = 0x6E, .max_sata_rate=MTB_UBM_SATA_RATE_NS, .max_sas_rate=MTB_UBM_SAS_RATE_NS, .max_pcie_rate=MTB_UBM_PCIE_5_RATE, },
			{ .drive_connector_idx=3, .slot_offset=3, .dfc_status_and_control=3, .drive_link_width=MTB_UBM_LINK_WIDTH_X4 , .port_type=MTB_UBM_PORT_TYPE_SEGREGATED, .domain=MTB_UBM_PORT_DOMAIN_PRIMARY, .hfc_identifier=1, .hfc_starting_phy_lane=0, .sff_ta_1001_support=1, .sas_sata_support=0, .quad_pcie_support=1, .dfc_empty=1, .ubm_ctrl_slave_addr = 0x6E, .max_sata_rate=MTB_UBM_SATA_RATE_NS, .max_sas_rate=MTB_UBM_SAS_RATE_NS, .max_pcie_rate=MTB_UBM_PCIE_5_RATE, },
			{ .drive_connector_idx=2, .slot_offset=2, .dfc_status_and_control=2, .drive_link_width=MTB_UBM_LINK_WIDTH_X4 , .port_type=MTB_UBM_PORT_TYPE_SEGREGATED, .domain=MTB_UBM_PORT_DOMAIN_PRIMARY, .hfc_identifier=1, .hfc_starting_phy_lane=4, .sff_ta_1001_support=1, .sas_sata_support=0, .quad_pcie_support=1, .dfc_empty=1, .ubm_ctrl_slave_addr = 0x6E, .max_sata_rate=MTB_UBM_SATA_RATE_NS, .max_sas_rate=MTB_UBM_SAS_RATE_NS, .max_pcie_rate=MTB_UBM_PCIE_5_RATE, },
			{ .drive_connector_idx=3, .slot_offset=3, .dfc_status_and_control=3, .drive_link_width=MTB_UBM_LINK_WIDTH_X1 , .port_type=MTB_UBM_PORT_TYPE_CONVERGED, .domain=MTB_UBM_PORT_DOMAIN_PRIMARY, .hfc_identifier=4, .hfc_starting_phy_lane=0, .sff_ta_1001_support=1, .sas_sata_support=1, .quad_pcie_support=0, .dfc_empty=1, .ubm_ctrl_slave_addr = 0x6E, .max_sata_rate=MTB_UBM_SATA_6GBS_RATE, .max_sas_rate=MTB_UBM_SAS_4_RATE, .max_pcie_rate=MTB_UBM_PCIE_5_RATE, },
			{ .drive_connector_idx=0, .slot_offset=0, .dfc_status_and_control=0, .drive_link_width=MTB_UBM_LINK_WIDTH_X1 , .port_type=MTB_UBM_PORT_TYPE_CONVERGED, .domain=MTB_UBM_PORT_DOMAIN_PRIMARY, .hfc_identifier=4, .hfc_starting_phy_lane=1, .sff_ta_1001_support=1, .sas_sata_support=1, .quad_pcie_support=0, .dfc_empty=1, .ubm_ctrl_slave_addr = 0x6E, .max_sata_rate=MTB_UBM_SATA_6GBS_RATE, .max_sas_rate=MTB_UBM_SAS_4_RATE, .max_pcie_rate=MTB_UBM_PCIE_5_RATE, },
			{ .drive_connector_idx=1, .slot_offset=1, .dfc_status_and_control=1, .drive_link_width=MTB_UBM_LINK_WIDTH_X1 , .port_type=MTB_UBM_PORT_TYPE_CONVERGED, .domain=MTB_UBM_PORT_DOMAIN_PRIMARY, .hfc_identifier=4, .hfc_starting_phy_lane=2, .sff_ta_1001_support=1, .sas_sata_support=1, .quad_pcie_support=0, .dfc_empty=1, .ubm_ctrl_slave_addr = 0x6E, .max_sata_rate=MTB_UBM_SATA_6GBS_RATE, .max_sas_rate=MTB_UBM_SAS_4_RATE, .max_pcie_rate=MTB_UBM_PCIE_5_RATE, },
			{ .drive_connector_idx=2, .slot_offset=2, .dfc_status_and_control=2, .drive_link_width=MTB_UBM_LINK_WIDTH_X1 , .port_type=MTB_UBM_PORT_TYPE_CONVERGED, .domain=MTB_UBM_PORT_DOMAIN_PRIMARY, .hfc_identifier=4, .hfc_starting_phy_lane=3, .sff_ta_1001_support=1, .sas_sata_support=1, .quad_pcie_support=0, .dfc_empty=1, .ubm_ctrl_slave_addr = 0x6E, .max_sata_rate=MTB_UBM_SATA_6GBS_RATE, .max_sas_rate=MTB_UBM_SAS_4_RATE, .max_pcie_rate=MTB_UBM_PCIE_5_RATE, },

	    }

**Comment by lieskov** [comment]
Hello Josh

This issue is applicable to the UBM-0.5.0 version only as this version doesn't support the Port Route Descriptors feature. For details see the RELEASE.md file of the UBM-0.5.0 (section Known issues/limitations).

Please try the UBM-1.0.0. This configuration parameter was renamed from hfc_routing to route_information, which is basically 
an array of the Port Route Information Descriptors.
